name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "* * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 718e4d08fd0183b4a3dc9e923c51171d
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
